
class Chunk:
	"""
	Represents a chunk of data generated by FastCDC algorithm
	"""

	__slots__ = ('offset', 'length', 'data', 'gear_hash')

	offset: int
	"""
	The offset of the chunk in bytes from the beginning of the input
	"""

	length: int
	"""
	The length of the chunk in bytes. The same as ``len(data)``
	"""

	data: memoryview
	"""
	Memory view of the chunk data

	.. caution::

		For chunks generated from ``cut_stream()``, this memory view is only guaranteed to be valid before the next chunk is generated

	.. note::

		For chunks generated from ``cut_files()``, this memory view will be pointed to part of an mmap object of the input file,
		which means the mmap object won't be released until all references to the generated chunk objects are released
	"""

	gear_hash: int
	"""
	FastCDC's gear hash for this chunk, range within uint64

	You should not use this hash for actual data deduplication since it's not guaranteed to be high quality
	"""

	def __init__(self, offset: int, length: int, data: memoryview, gear_hash: int):
		self.offset = offset
		self.length = length
		self.data = data
		self.gear_hash = gear_hash

	def __repr__(self) -> str:
		return f'<{self.__class__.__name__} offset={self.offset} length={self.length} gear_hash={self.gear_hash}>'
