from pathlib import Path
from typing import Optional, Union, Iterator

from pyfastcdc.common import NormalizedChunking, BinaryStreamReader, Chunk


class FastCDC:
	"""
	The FastCDC 2020 chunker implementation (cython version)
	"""

	def __init__(
			self,
			avg_size: int = 16384,
			*,
			min_size: Optional[int] = None,
			max_size: Optional[int] = None,
			normalized_chunking: NormalizedChunking = 1,
			seed: int = 0,
	):
		...

	def cut_buf(self, buf: Union[bytes, bytearray, memoryview]) -> Iterator[Chunk]:
		"""
		Cut the given buffer with FastCDC algorithm

		:param buf: The input buffer to be processed
		:return: An iterator that yields ``Chunk`` objects
		"""
		...

	def cut_file(self, file_path: Union[str, bytes, Path]) -> Iterator[Chunk]:
		"""
		Cut the given file with FastCDC algorithm

		:param file_path: Path to the file to be processed. It should be a readable regular file
		:return: An iterator that yields ``Chunk`` objects
		"""
		...

	def cut_stream(self, stream: BinaryStreamReader) -> Iterator[Chunk]:
		"""
		Cut the given stream with FastCDC algorithm

		.. caution::

			All chunks generated by this method have their `.data` fields guaranteed to be valid before and only before the next chunk is generated

		:param stream: The input stream to be processed. It needs to have any of the following methods:

		* ``read(self, n: int) -> bytes``
		* ``readinto(self, b: memoryview) -> int``  (preferred)

		:return: An iterator that yields ``Chunk`` objects
		"""
		...

	@property
	def avg_size(self) -> int:
		...

	@property
	def min_size(self) -> int:
		...

	@property
	def max_size(self) -> int:
		...
