import dataclasses
from typing import Union

from typing_extensions import Literal, Protocol


@dataclasses.dataclass(frozen=True)
class Chunk:
	"""
	Represents a chunk of data generated by FastCDC algorithm
	"""

	gear_hash: int
	"""
	FastCDC's gear hash for this chunk, range within uint64
	
	You should not use this hash for actual data deduplication
	"""

	offset: int
	"""
	The offset of the chunk in bytes from the beginning of the input
	"""

	length: int
	"""
	The length of the chunk in bytes. The same as ``len(data)``
	"""

	data: memoryview
	"""
	Memory view of the chunk data
	
	.. caution::
	
		For chunks generated from ``cut_stream()``, this memory view is only guaranteed to be valid before the next chunk is generated
		
	.. note::
	
		For chunks generated from ``cut_files()``, this memory view will be pointed to part of an mmap object of the input file,
		which means the mmap object won't be released until all references to the generated chunk objects are released
	"""


class _BinaryStreamReaderWithRead(Protocol):
	def read(self, n: int) -> bytes: ...


class _BinaryStreamReaderWithReadinto(Protocol):
	def readinto(self, b: memoryview) -> int: ...


BinaryStreamReader = Union[_BinaryStreamReaderWithRead, _BinaryStreamReaderWithReadinto]
NormalizedChunking = Literal[0, 1, 2, 3]
